apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sketchcabs-ingress
  namespace: sketchcabs
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  tls:
    - hosts:
        - sketchcabs.com
        - www.sketchcabs.com
      secretName: sketchcabs-tls
  rules:
    - host: sketchcabs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sketchcabs-web
                port:
                  number: 80
    - host: www.sketchcabs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sketchcabs-web
                port:
                  number: 80
